@echo off
SET SERVIDOR=SERVIDOR01\SQLEXPRESS
SET DATABASE=BRASIL
SET USUSQL=admin
SET PWDSQL=admin
SET CAMINHO_BAK=G:\Backup\DB-BRASIL
SET ARQ_BAK=BRASIL

del "%CAMINHO_BAK%\%ARQ_BAK%.BAK"
"C:\Arquivos de programas\Microsoft SQL Server\90\Tools\Binn\OSQL.EXE" -S %SERVIDOR% -U %USUSQL% -P %PWDSQL% -Q "BACKUP DATABASE %DATABASE% TO DISK ='%CAMINHO_BAK%\%ARQ_BAK%.BAK'"
"C:\Arquivos de programas\WinRAR\WinRAR.exe" a -u -r -dh -agYYYYMMMDD "%CAMINHO_BAK%\%ARQ_BAK%.rar" "%CAMINHO_BAK%\%ARQ_BAK%.BAK"

@echo